/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IPhoneNumberResolver,
  IPhoneNumberResolverInterface,
} from "../IPhoneNumberResolver";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "fqdn",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "host",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "domain",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "tld",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        indexed: false,
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "SetPhoneNumber",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "host",
        type: "string",
      },
      {
        internalType: "string",
        name: "domain",
        type: "string",
      },
      {
        internalType: "string",
        name: "tld",
        type: "string",
      },
    ],
    name: "phoneNumber",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "fqdn",
        type: "string",
      },
    ],
    name: "phoneNumber",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "fqdn",
        type: "bytes32",
      },
    ],
    name: "phoneNumber",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "host",
        type: "string",
      },
      {
        internalType: "string",
        name: "domain",
        type: "string",
      },
      {
        internalType: "string",
        name: "tld",
        type: "string",
      },
      {
        internalType: "bytes",
        name: "payload",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "signature",
        type: "bytes",
      },
    ],
    name: "setPhoneNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPhoneNumberResolver__factory {
  static readonly abi = _abi;
  static createInterface(): IPhoneNumberResolverInterface {
    return new utils.Interface(_abi) as IPhoneNumberResolverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPhoneNumberResolver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IPhoneNumberResolver;
  }
}
