/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface AddressResolverInterface extends ethers.utils.Interface {
  functions: {
    "MAX_LABEL_LENGTH()": FunctionFragment;
    "MIN_LABEL_LENGTH()": FunctionFragment;
    "addr(bytes,bytes,bytes,uint256)": FunctionFragment;
    "setAddr(bytes,bytes,bytes,uint256,bytes)": FunctionFragment;
    "setAddr_SYNC(bytes,bytes,bytes,uint256,bytes)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "valid(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addr",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddr",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddr_SYNC",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "valid",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddr_SYNC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valid", data: BytesLike): Result;

  events: {
    "SetAddress(bytes,bytes,bytes,uint256,bytes)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetAddress"): EventFragment;
}

export type SetAddressEvent = TypedEvent<
  [string, string, string, BigNumber, string] & {
    host: string;
    domain: string;
    tld: string;
    coin: BigNumber;
    address_: string;
  }
>;

export class AddressResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: AddressResolverInterface;

  functions: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    "addr(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "addr(bytes,uint256)"(
      fqdn_: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "addr(bytes,bytes,uint256)"(
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "addr(bytes32,uint256)"(
      fqdn: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    setAddr(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAddr_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  "addr(bytes,bytes,bytes,uint256)"(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "addr(bytes,uint256)"(
    fqdn_: BytesLike,
    coin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "addr(bytes,bytes,uint256)"(
    domain: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "addr(bytes32,uint256)"(
    fqdn: BytesLike,
    coin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  setAddr(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    address_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAddr_SYNC(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    address_: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(string,string,string)"(
    host: string,
    arg1: string,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(string,string)"(
    domain: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(bytes,bytes)"(
    domain: BytesLike,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(bytes,bytes,bytes)"(
    host: BytesLike,
    arg1: BytesLike,
    arg2: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "addr(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "addr(bytes,uint256)"(
      fqdn_: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "addr(bytes,bytes,uint256)"(
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "addr(bytes32,uint256)"(
      fqdn: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    setAddr(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setAddr_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "SetAddress(bytes,bytes,bytes,uint256,bytes)"(
      host?: null,
      domain?: null,
      tld?: null,
      coin?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        host: string;
        domain: string;
        tld: string;
        coin: BigNumber;
        address_: string;
      }
    >;

    SetAddress(
      host?: null,
      domain?: null,
      tld?: null,
      coin?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        host: string;
        domain: string;
        tld: string;
        coin: BigNumber;
        address_: string;
      }
    >;
  };

  estimateGas: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "addr(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addr(bytes,uint256)"(
      fqdn_: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addr(bytes,bytes,uint256)"(
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addr(bytes32,uint256)"(
      fqdn: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAddr(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAddr_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "addr(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addr(bytes,uint256)"(
      fqdn_: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addr(bytes,bytes,uint256)"(
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addr(bytes32,uint256)"(
      fqdn: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAddr(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAddr_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
