/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface NFTResolverInterface extends ethers.utils.Interface {
  functions: {
    "MAX_LABEL_LENGTH()": FunctionFragment;
    "MIN_LABEL_LENGTH()": FunctionFragment;
    "nft(bytes32,uint256)": FunctionFragment;
    "setNFT(bytes,bytes,bytes,uint256,address,uint256)": FunctionFragment;
    "setNFT_SYNC(bytes,bytes,bytes,uint256,address,uint256)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "valid(string,string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "MAX_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nft",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setNFT",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setNFT_SYNC",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "valid",
    values: [string, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setNFT_SYNC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valid", data: BytesLike): Result;

  events: {
    "SetNFT(bytes,bytes,bytes,bytes,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SetNFT"): EventFragment;
}

export type SetNFTEvent = TypedEvent<
  [string, string, string, string, BigNumber, string, BigNumber] & {
    fqdn: string;
    host: string;
    domain: string;
    tld: string;
    chainId: BigNumber;
    contractAddress: string;
    tokenId: BigNumber;
  }
>;

export class NFTResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: NFTResolverInterface;

  functions: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    "nft(bytes32,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[string, BigNumber] & { contract_: string; tokenId: BigNumber }]
    >;

    "nft(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[string, BigNumber] & { contract_: string; tokenId: BigNumber }]
    >;

    "nft(bytes,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[string, BigNumber] & { contract_: string; tokenId: BigNumber }]
    >;

    setNFT(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNFT_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  "nft(bytes32,uint256)"(
    fqdn: BytesLike,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

  "nft(bytes,bytes,bytes,uint256)"(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

  "nft(bytes,uint256)"(
    fqdn: BytesLike,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

  setNFT(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    contract_: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNFT_SYNC(
    host: BytesLike,
    domain: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    contract_: string,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(string,string,string)"(
    host: string,
    arg1: string,
    arg2: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(string,string)"(
    domain: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(bytes,bytes)"(
    domain: BytesLike,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "valid(bytes,bytes,bytes)"(
    host: BytesLike,
    arg1: BytesLike,
    arg2: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "nft(bytes32,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

    "nft(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

    "nft(bytes,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

    setNFT(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setNFT_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "SetNFT(bytes,bytes,bytes,bytes,uint256,address,uint256)"(
      fqdn?: null,
      host?: null,
      domain?: null,
      tld?: null,
      chainId?: null,
      contractAddress?: null,
      tokenId?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber, string, BigNumber],
      {
        fqdn: string;
        host: string;
        domain: string;
        tld: string;
        chainId: BigNumber;
        contractAddress: string;
        tokenId: BigNumber;
      }
    >;

    SetNFT(
      fqdn?: null,
      host?: null,
      domain?: null,
      tld?: null,
      chainId?: null,
      contractAddress?: null,
      tokenId?: null
    ): TypedEventFilter<
      [string, string, string, string, BigNumber, string, BigNumber],
      {
        fqdn: string;
        host: string;
        domain: string;
        tld: string;
        chainId: BigNumber;
        contractAddress: string;
        tokenId: BigNumber;
      }
    >;
  };

  estimateGas: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    "nft(bytes32,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nft(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "nft(bytes,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setNFT(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNFT_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "nft(bytes32,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nft(bytes,bytes,bytes,uint256)"(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "nft(bytes,uint256)"(
      fqdn: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setNFT(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNFT_SYNC(
      host: BytesLike,
      domain: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(string,string,string)"(
      host: string,
      arg1: string,
      arg2: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(string,string)"(
      domain: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(bytes,bytes)"(
      domain: BytesLike,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "valid(bytes,bytes,bytes)"(
      host: BytesLike,
      arg1: BytesLike,
      arg2: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
