/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IRootInterface extends ethers.utils.Interface {
  functions: {
    "getAuthorizer()": FunctionFragment;
    "getResolver(bytes)": FunctionFragment;
    "isEnable(bytes)": FunctionFragment;
    "register(uint8[],bytes,address,uint64,address,bool,uint8)": FunctionFragment;
    "renew(bytes,uint64)": FunctionFragment;
    "setAuthorizer(address)": FunctionFragment;
    "setControllerApproval(bytes32,address,bool)": FunctionFragment;
    "setEnable(bytes,bool)": FunctionFragment;
    "setResolver(bytes,address)": FunctionFragment;
    "setWrapper(bytes32,bool,address)": FunctionFragment;
    "transfer(bytes,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAuthorizer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getResolver",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "isEnable", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      BigNumberish[],
      BytesLike,
      string,
      BigNumberish,
      string,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "renew",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorizer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setControllerApproval",
    values: [BytesLike, string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnable",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setResolver",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setWrapper",
    values: [BytesLike, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAuthorizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isEnable", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setControllerApproval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setEnable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setResolver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setWrapper", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;

  events: {
    "NewAuthorizer(address)": EventFragment;
    "TldRegistered(bytes,address,uint256)": EventFragment;
    "TldRenewed(bytes,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewAuthorizer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TldRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TldRenewed"): EventFragment;
}

export type NewAuthorizerEvent = TypedEvent<[string] & { address_: string }>;

export type TldRegisteredEvent = TypedEvent<
  [string, string, BigNumber] & {
    tld: string;
    owner: string;
    expiry: BigNumber;
  }
>;

export type TldRenewedEvent = TypedEvent<
  [string, BigNumber] & { tld: string; expiry: BigNumber }
>;

export class IRoot extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IRootInterface;

  functions: {
    getAuthorizer(overrides?: CallOverrides): Promise<[string]>;

    getResolver(tld: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    isEnable(tld: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    register(
      chains: BigNumberish[],
      tld: BytesLike,
      resolver: string,
      expiry: BigNumberish,
      owner: string,
      enable: boolean,
      class_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renew(
      tld: BytesLike,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAuthorizer(
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setControllerApproval(
      tld: BytesLike,
      controller: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEnable(
      tld: BytesLike,
      enable: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setResolver(
      tld: BytesLike,
      resolver: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setWrapper(
      tld: BytesLike,
      enable: boolean,
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transfer(
      tld: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getAuthorizer(overrides?: CallOverrides): Promise<string>;

  getResolver(tld: BytesLike, overrides?: CallOverrides): Promise<string>;

  isEnable(tld: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  register(
    chains: BigNumberish[],
    tld: BytesLike,
    resolver: string,
    expiry: BigNumberish,
    owner: string,
    enable: boolean,
    class_: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renew(
    tld: BytesLike,
    expiry: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAuthorizer(
    address_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setControllerApproval(
    tld: BytesLike,
    controller: string,
    approved: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEnable(
    tld: BytesLike,
    enable: boolean,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setResolver(
    tld: BytesLike,
    resolver: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setWrapper(
    tld: BytesLike,
    enable: boolean,
    address_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transfer(
    tld: BytesLike,
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getAuthorizer(overrides?: CallOverrides): Promise<string>;

    getResolver(tld: BytesLike, overrides?: CallOverrides): Promise<string>;

    isEnable(tld: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    register(
      chains: BigNumberish[],
      tld: BytesLike,
      resolver: string,
      expiry: BigNumberish,
      owner: string,
      enable: boolean,
      class_: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renew(
      tld: BytesLike,
      expiry: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setAuthorizer(address_: string, overrides?: CallOverrides): Promise<void>;

    setControllerApproval(
      tld: BytesLike,
      controller: string,
      approved: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setEnable(
      tld: BytesLike,
      enable: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setResolver(
      tld: BytesLike,
      resolver: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setWrapper(
      tld: BytesLike,
      enable: boolean,
      address_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transfer(
      tld: BytesLike,
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "NewAuthorizer(address)"(
      address_?: null
    ): TypedEventFilter<[string], { address_: string }>;

    NewAuthorizer(
      address_?: null
    ): TypedEventFilter<[string], { address_: string }>;

    "TldRegistered(bytes,address,uint256)"(
      tld?: null,
      owner?: null,
      expiry?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { tld: string; owner: string; expiry: BigNumber }
    >;

    TldRegistered(
      tld?: null,
      owner?: null,
      expiry?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { tld: string; owner: string; expiry: BigNumber }
    >;

    "TldRenewed(bytes,uint256)"(
      tld?: null,
      expiry?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { tld: string; expiry: BigNumber }
    >;

    TldRenewed(
      tld?: null,
      expiry?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { tld: string; expiry: BigNumber }
    >;
  };

  estimateGas: {
    getAuthorizer(overrides?: CallOverrides): Promise<BigNumber>;

    getResolver(tld: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    isEnable(tld: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    register(
      chains: BigNumberish[],
      tld: BytesLike,
      resolver: string,
      expiry: BigNumberish,
      owner: string,
      enable: boolean,
      class_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renew(
      tld: BytesLike,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAuthorizer(
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setControllerApproval(
      tld: BytesLike,
      controller: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEnable(
      tld: BytesLike,
      enable: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setResolver(
      tld: BytesLike,
      resolver: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setWrapper(
      tld: BytesLike,
      enable: boolean,
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transfer(
      tld: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAuthorizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getResolver(
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isEnable(
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    register(
      chains: BigNumberish[],
      tld: BytesLike,
      resolver: string,
      expiry: BigNumberish,
      owner: string,
      enable: boolean,
      class_: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renew(
      tld: BytesLike,
      expiry: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAuthorizer(
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setControllerApproval(
      tld: BytesLike,
      controller: string,
      approved: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEnable(
      tld: BytesLike,
      enable: boolean,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setResolver(
      tld: BytesLike,
      resolver: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setWrapper(
      tld: BytesLike,
      enable: boolean,
      address_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transfer(
      tld: BytesLike,
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
