/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface PublicResolverInterface extends ethers.utils.Interface {
  functions: {
    "ADMIN_ROLE()": FunctionFragment;
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "MAX_LABEL_LENGTH()": FunctionFragment;
    "MIN_LABEL_LENGTH()": FunctionFragment;
    "getAddress(bytes,bytes,bytes)": FunctionFragment;
    "getMortgage()": FunctionFragment;
    "getMultiCoinAddress(bytes,bytes,bytes,uint256)": FunctionFragment;
    "getNFT(bytes,bytes,bytes,uint256)": FunctionFragment;
    "getReverseAddress(address)": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getSynchronizer()": FunctionFragment;
    "getText(bytes,bytes,bytes)": FunctionFragment;
    "getTypedText(bytes,bytes,bytes,bytes)": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "receiveSync(bytes)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setAddress(bytes,bytes,bytes,address)": FunctionFragment;
    "setMortgage(address)": FunctionFragment;
    "setMultiCoinAddress(bytes,bytes,bytes,uint256,bytes)": FunctionFragment;
    "setNFT(bytes,bytes,bytes,uint256,address,uint256)": FunctionFragment;
    "setReverseAddress(bytes,bytes,bytes,address)": FunctionFragment;
    "setSynchronizer(address)": FunctionFragment;
    "setText(bytes,bytes,bytes,string)": FunctionFragment;
    "setTypedText(bytes,bytes,bytes,bytes,string)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "unsetAddress(bytes,bytes,bytes)": FunctionFragment;
    "unsetMultiCoinAddress(bytes,bytes,bytes,uint256)": FunctionFragment;
    "unsetNFT(bytes,bytes,bytes,uint256)": FunctionFragment;
    "unsetReverseAddress(bytes,bytes,bytes,address)": FunctionFragment;
    "unsetText(bytes,bytes,bytes)": FunctionFragment;
    "unsetTypedText(bytes,bytes,bytes,bytes)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "valid(bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LABEL_LENGTH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMortgage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMultiCoinAddress",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNFT",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReverseAddress",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSynchronizer",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getText",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTypedText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveSync",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(functionFragment: "setMortgage", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMultiCoinAddress",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNFT",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setReverseAddress",
    values: [BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSynchronizer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setText",
    values: [BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTypedText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetAddress",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetMultiCoinAddress",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetNFT",
    values: [BytesLike, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetReverseAddress",
    values: [BytesLike, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetText",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsetTypedText",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "valid", values: [BytesLike]): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LABEL_LENGTH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMortgage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultiCoinAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReverseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSynchronizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getText", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTypedText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveSync",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMortgage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMultiCoinAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setReverseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSynchronizer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setText", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTypedText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsetAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsetMultiCoinAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unsetNFT", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsetReverseAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unsetText", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unsetTypedText",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "valid", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "ExecuteSync(bool,bytes)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "RequestSync(bytes)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "SetAddress(bytes,bytes,bytes,address)": EventFragment;
    "SetMultiCoinAddress(bytes,bytes,bytes,uint256,bytes)": EventFragment;
    "SetNFT(bytes,bytes,bytes,uint256,address,uint256)": EventFragment;
    "SetReverseAddress(bytes,bytes,bytes,address)": EventFragment;
    "SetText(bytes,bytes,bytes,string)": EventFragment;
    "SetTypedText(bytes,bytes,bytes,bytes,string)": EventFragment;
    "SyncError(bytes,bytes)": EventFragment;
    "UnsetAddress(bytes,bytes,bytes)": EventFragment;
    "UnsetMultiCoinAddress(bytes,bytes,bytes,uint256)": EventFragment;
    "UnsetNFT(bytes,bytes,bytes,uint256)": EventFragment;
    "UnsetReverseAddress(bytes,bytes,bytes,address)": EventFragment;
    "UnsetText(bytes,bytes,bytes)": EventFragment;
    "UnsetTypedText(bytes,bytes,bytes,bytes)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecuteSync"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RequestSync"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMultiCoinAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetReverseAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetText"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetTypedText"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SyncError"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetMultiCoinAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetNFT"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetReverseAddress"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetText"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UnsetTypedText"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string] & { previousAdmin: string; newAdmin: string }
>;

export type BeaconUpgradedEvent = TypedEvent<[string] & { beacon: string }>;

export type ExecuteSyncEvent = TypedEvent<
  [boolean, string] & { success: boolean; ews: string }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type RequestSyncEvent = TypedEvent<[string] & { ews: string }>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string] & {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type SetAddressEvent = TypedEvent<
  [string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    address_: string;
  }
>;

export type SetMultiCoinAddressEvent = TypedEvent<
  [string, string, string, BigNumber, string] & {
    host: string;
    name: string;
    tld: string;
    coin: BigNumber;
    address_: string;
  }
>;

export type SetNFTEvent = TypedEvent<
  [string, string, string, BigNumber, string, BigNumber] & {
    host: string;
    name: string;
    tld: string;
    chainId: BigNumber;
    contractAddress: string;
    tokenId: BigNumber;
  }
>;

export type SetReverseAddressEvent = TypedEvent<
  [string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    address_: string;
  }
>;

export type SetTextEvent = TypedEvent<
  [string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    text: string;
  }
>;

export type SetTypedTextEvent = TypedEvent<
  [string, string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    type_: string;
    text: string;
  }
>;

export type SyncErrorEvent = TypedEvent<
  [string, string] & { ews: string; reason: string }
>;

export type UnsetAddressEvent = TypedEvent<
  [string, string, string] & { host: string; name: string; tld: string }
>;

export type UnsetMultiCoinAddressEvent = TypedEvent<
  [string, string, string, BigNumber] & {
    host: string;
    name: string;
    tld: string;
    coin: BigNumber;
  }
>;

export type UnsetNFTEvent = TypedEvent<
  [string, string, string, BigNumber] & {
    host: string;
    name: string;
    tld: string;
    chainId: BigNumber;
  }
>;

export type UnsetReverseAddressEvent = TypedEvent<
  [string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    address_: string;
  }
>;

export type UnsetTextEvent = TypedEvent<
  [string, string, string] & { host: string; name: string; tld: string }
>;

export type UnsetTypedTextEvent = TypedEvent<
  [string, string, string, string] & {
    host: string;
    name: string;
    tld: string;
    type_: string;
  }
>;

export type UpgradedEvent = TypedEvent<[string] & { implementation: string }>;

export class PublicResolver extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: PublicResolverInterface;

  functions: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getMortgage(overrides?: CallOverrides): Promise<[string]>;

    getMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [[string, BigNumber] & { contract_: string; tokenId: BigNumber }]
    >;

    getReverseAddress(
      address_: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getSynchronizer(overrides?: CallOverrides): Promise<[string]>;

    getText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      registry_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    receiveSync(
      ews: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMortgage(
      mortgage_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSynchronizer(
      synchronizer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    unsetAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unsetMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unsetNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unsetReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unsetText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    unsetTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    valid(label: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;
  };

  ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

  getAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getMortgage(overrides?: CallOverrides): Promise<string>;

  getMultiCoinAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getNFT(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

  getReverseAddress(
    address_: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getSynchronizer(overrides?: CallOverrides): Promise<string>;

  getText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getTypedText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    type_: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  initialize(
    registry_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  receiveSync(
    ews: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    address_: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMortgage(
    mortgage_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setMultiCoinAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    address_: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setNFT(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    contract_: string,
    tokenId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setReverseAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    address_: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSynchronizer(
    synchronizer_: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    text: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTypedText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    type_: BytesLike,
    text: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceID: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  unsetAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unsetMultiCoinAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    coin: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unsetNFT(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    chainId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unsetReverseAddress(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    address_: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unsetText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  unsetTypedText(
    host: BytesLike,
    name: BytesLike,
    tld: BytesLike,
    type_: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  valid(label: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    getAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getMortgage(overrides?: CallOverrides): Promise<string>;

    getMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { contract_: string; tokenId: BigNumber }>;

    getReverseAddress(
      address_: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getSynchronizer(overrides?: CallOverrides): Promise<string>;

    getText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    initialize(registry_: string, overrides?: CallOverrides): Promise<void>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    receiveSync(ews: BytesLike, overrides?: CallOverrides): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setMortgage(mortgage_: string, overrides?: CallOverrides): Promise<void>;

    setMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSynchronizer(
      synchronizer_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      text: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    unsetAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unsetMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unsetNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    unsetReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: CallOverrides
    ): Promise<void>;

    unsetText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    unsetTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    valid(label: BytesLike, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    "ExecuteSync(bool,bytes)"(
      success?: null,
      ews?: null
    ): TypedEventFilter<[boolean, string], { success: boolean; ews: string }>;

    ExecuteSync(
      success?: null,
      ews?: null
    ): TypedEventFilter<[boolean, string], { success: boolean; ews: string }>;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "RequestSync(bytes)"(
      ews?: null
    ): TypedEventFilter<[string], { ews: string }>;

    RequestSync(ews?: null): TypedEventFilter<[string], { ews: string }>;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "SetAddress(bytes,bytes,bytes,address)"(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    SetAddress(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    "SetMultiCoinAddress(bytes,bytes,bytes,uint256,bytes)"(
      host?: null,
      name?: null,
      tld?: null,
      coin?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        host: string;
        name: string;
        tld: string;
        coin: BigNumber;
        address_: string;
      }
    >;

    SetMultiCoinAddress(
      host?: null,
      name?: null,
      tld?: null,
      coin?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string],
      {
        host: string;
        name: string;
        tld: string;
        coin: BigNumber;
        address_: string;
      }
    >;

    "SetNFT(bytes,bytes,bytes,uint256,address,uint256)"(
      host?: null,
      name?: null,
      tld?: null,
      chainId?: null,
      contractAddress?: null,
      tokenId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string, BigNumber],
      {
        host: string;
        name: string;
        tld: string;
        chainId: BigNumber;
        contractAddress: string;
        tokenId: BigNumber;
      }
    >;

    SetNFT(
      host?: null,
      name?: null,
      tld?: null,
      chainId?: null,
      contractAddress?: null,
      tokenId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, string, BigNumber],
      {
        host: string;
        name: string;
        tld: string;
        chainId: BigNumber;
        contractAddress: string;
        tokenId: BigNumber;
      }
    >;

    "SetReverseAddress(bytes,bytes,bytes,address)"(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    SetReverseAddress(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    "SetText(bytes,bytes,bytes,string)"(
      host?: null,
      name?: null,
      tld?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; text: string }
    >;

    SetText(
      host?: null,
      name?: null,
      tld?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; text: string }
    >;

    "SetTypedText(bytes,bytes,bytes,bytes,string)"(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      { host: string; name: string; tld: string; type_: string; text: string }
    >;

    SetTypedText(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null,
      text?: null
    ): TypedEventFilter<
      [string, string, string, string, string],
      { host: string; name: string; tld: string; type_: string; text: string }
    >;

    "SyncError(bytes,bytes)"(
      ews?: null,
      reason?: null
    ): TypedEventFilter<[string, string], { ews: string; reason: string }>;

    SyncError(
      ews?: null,
      reason?: null
    ): TypedEventFilter<[string, string], { ews: string; reason: string }>;

    "UnsetAddress(bytes,bytes,bytes)"(
      host?: null,
      name?: null,
      tld?: null
    ): TypedEventFilter<
      [string, string, string],
      { host: string; name: string; tld: string }
    >;

    UnsetAddress(
      host?: null,
      name?: null,
      tld?: null
    ): TypedEventFilter<
      [string, string, string],
      { host: string; name: string; tld: string }
    >;

    "UnsetMultiCoinAddress(bytes,bytes,bytes,uint256)"(
      host?: null,
      name?: null,
      tld?: null,
      coin?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { host: string; name: string; tld: string; coin: BigNumber }
    >;

    UnsetMultiCoinAddress(
      host?: null,
      name?: null,
      tld?: null,
      coin?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { host: string; name: string; tld: string; coin: BigNumber }
    >;

    "UnsetNFT(bytes,bytes,bytes,uint256)"(
      host?: null,
      name?: null,
      tld?: null,
      chainId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { host: string; name: string; tld: string; chainId: BigNumber }
    >;

    UnsetNFT(
      host?: null,
      name?: null,
      tld?: null,
      chainId?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber],
      { host: string; name: string; tld: string; chainId: BigNumber }
    >;

    "UnsetReverseAddress(bytes,bytes,bytes,address)"(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    UnsetReverseAddress(
      host?: null,
      name?: null,
      tld?: null,
      address_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; address_: string }
    >;

    "UnsetText(bytes,bytes,bytes)"(
      host?: null,
      name?: null,
      tld?: null
    ): TypedEventFilter<
      [string, string, string],
      { host: string; name: string; tld: string }
    >;

    UnsetText(
      host?: null,
      name?: null,
      tld?: null
    ): TypedEventFilter<
      [string, string, string],
      { host: string; name: string; tld: string }
    >;

    "UnsetTypedText(bytes,bytes,bytes,bytes)"(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; type_: string }
    >;

    UnsetTypedText(
      host?: null,
      name?: null,
      tld?: null,
      type_?: null
    ): TypedEventFilter<
      [string, string, string, string],
      { host: string; name: string; tld: string; type_: string }
    >;

    "Upgraded(address)"(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;
  };

  estimateGas: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<BigNumber>;

    getAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getMortgage(overrides?: CallOverrides): Promise<BigNumber>;

    getMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getReverseAddress(
      address_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSynchronizer(overrides?: CallOverrides): Promise<BigNumber>;

    getText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      registry_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    receiveSync(
      ews: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMortgage(
      mortgage_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSynchronizer(
      synchronizer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unsetAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unsetMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unsetNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unsetReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unsetText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    unsetTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    valid(label: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    ADMIN_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    MIN_LABEL_LENGTH(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getMortgage(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getReverseAddress(
      address_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSynchronizer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      registry_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    receiveSync(
      ews: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMortgage(
      mortgage_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      address_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      contract_: string,
      tokenId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSynchronizer(
      synchronizer_: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      text: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceID: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unsetAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unsetMultiCoinAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      coin: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unsetNFT(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      chainId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unsetReverseAddress(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      address_: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unsetText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    unsetTypedText(
      host: BytesLike,
      name: BytesLike,
      tld: BytesLike,
      type_: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    valid(
      label: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
